apiVersion: v1
kind: PersistentVolume
metadata:
  name: datasets-pv
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: kubeflow-user-example-com
    name: datasets-pvc
  nfs:
    path: /srv/nfs/datasets
    server: 10.11.12.2